/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Menu.Menu;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projetonestle.TextPrompt;

/**
 *
 * @author LEANDRO
 */
public class TelaLogin extends javax.swing.JFrame {
            LinkedList email = new LinkedList();
            LinkedList senha = new LinkedList();
            LinkedList nome = new LinkedList();
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        TextPrompt placeholder = new TextPrompt("E-mail", Login);
        TextPrompt placeholder1 = new TextPrompt("Senha", Senha);
        OlhoFechado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        OlhoFechado = new javax.swing.JLabel();
        OlhoAberto = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        Menu = new javax.swing.JLabel();
        Login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 584, 50, 30);

        OlhoFechado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/olhofechado.png"))); // NOI18N
        OlhoFechado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OlhoFechado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OlhoFechadoMouseClicked(evt);
            }
        });
        getContentPane().add(OlhoFechado);
        OlhoFechado.setBounds(560, 310, 40, 30);

        OlhoAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagem1.png"))); // NOI18N
        OlhoAberto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OlhoAberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OlhoAbertoMouseClicked(evt);
            }
        });
        getContentPane().add(OlhoAberto);
        OlhoAberto.setBounds(360, 310, 30, 20);

        BtnLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Login");
        BtnLogin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLoginMouseExited(evt);
            }
        });
        getContentPane().add(BtnLogin);
        BtnLogin.setBounds(520, 400, 70, 50);

        Senha.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Senha.setBorder(null);
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SenhaKeyPressed(evt);
            }
        });
        getContentPane().add(Senha);
        Senha.setBounds(370, 340, 200, 30);

        Menu.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Menu");
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuMouseExited(evt);
            }
        });
        getContentPane().add(Menu);
        Menu.setBounds(360, 410, 80, 50);

        Login.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Login.setBorder(null);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(370, 220, 200, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Screenshot_29.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 651, 653);

        setSize(new java.awt.Dimension(667, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void OlhoAbertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlhoAbertoMouseClicked
        Senha.setEchoChar((char) 0);
        OlhoFechado.setVisible(true);
        OlhoAberto.setVisible(false);
        
    }//GEN-LAST:event_OlhoAbertoMouseClicked

    private void OlhoFechadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlhoFechadoMouseClicked
        Senha.setEchoChar('*'); 
        OlhoFechado.setVisible(false);
        OlhoAberto.setVisible(true);
    }//GEN-LAST:event_OlhoFechadoMouseClicked

    private void MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseEntered
    Menu.setForeground(Color.black);
    }//GEN-LAST:event_MenuMouseEntered

    private void MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseExited
         Menu.setForeground(Color.white);
    }//GEN-LAST:event_MenuMouseExited

    private void BtnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseEntered
        BtnLogin.setForeground(Color.black);
    }//GEN-LAST:event_BtnLoginMouseEntered

    private void BtnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseExited
        BtnLogin.setForeground(Color.white);
    }//GEN-LAST:event_BtnLoginMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try{
        Desktop.getDesktop().browse(new URL("https://www.nestleporvoce.com.br/?gclid=CjwKCAjwr7X4BRA4EiwAUXjbt92sphs5HenSAOZrzeXHCCX6D2Lt5HWJy830vVHzfgmStQzAGoWWPxoC780QAvD_BwE").toURI());
       }
       catch (IOException | URISyntaxException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked
private boolean buscarRelacao(LinkedList email, LinkedList senha){
        int nEmail = -1;
        for (int i = 0; i < email.size(); i++) {
            if (Login.getText().equals(email.get(i))){
                nEmail = i;
            }
        } 
        try{
        return senha.get(nEmail).equals(Senha.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Login ou senha incorreto(a).");
        }
        return false;
    }

private int buscarRelacaoInt(LinkedList email){
        int nEmail = -1;
        for (int i = 0; i < email.size(); i++) {
            if (Login.getText().equals(email.get(i))){
                nEmail = i;
            }
        } 
        
        return nEmail;
    }
     
    
    private void BtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseClicked
      
        try {
            File senhas = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosSenhas.txt");
            File emails = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosEmails.txt");
            File nomes = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosNomes.txt");
                senha.clear();
                email.clear();
                
            Scanner scsenha = new Scanner(senhas);
            Scanner scemail = new Scanner(emails);
            Scanner scnumero = new Scanner(nomes);
            while(scsenha.hasNext() && scemail.hasNext() && scnumero.hasNext()){
                senha.add(scsenha.nextLine());
                email.add(scemail.nextLine());
                nome.add(scnumero.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } 
        if (buscarRelacao(email, senha)){
            JOptionPane.showMessageDialog(rootPane, "Login realizado. Seja bem-vindo(a), "+nome.get(buscarRelacaoInt(email))+"!");
            dispose();
        }
        
    }//GEN-LAST:event_BtnLoginMouseClicked

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_MenuMouseClicked

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            File senhas = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosSenhas.txt");
            File emails = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosEmails.txt");
            File nomes = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosNomes.txt");
                senha.clear();
                email.clear();
                
            Scanner scsenha = new Scanner(senhas);
            Scanner scemail = new Scanner(emails);
            Scanner scnumero = new Scanner(nomes);
            while(scsenha.hasNext() && scemail.hasNext() && scnumero.hasNext()){
                senha.add(scsenha.nextLine());
                email.add(scemail.nextLine());
                nome.add(scnumero.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } 
        if (buscarRelacao(email, senha)){
            JOptionPane.showMessageDialog(rootPane, "Login realizado. Seja bem-vindo(a), "+nome.get(buscarRelacaoInt(email))+"!");
            dispose();
        }
        }
    }//GEN-LAST:event_LoginKeyPressed

    private void SenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SenhaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
            File senhas = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosSenhas.txt");
            File emails = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosEmails.txt");
            File nomes = new File("C:\\Users\\LEANDRO\\Documents\\NetBeansProjects\\ProjetoNestle\\registrosNomes.txt");
                senha.clear();
                email.clear();
                
            Scanner scsenha = new Scanner(senhas);
            Scanner scemail = new Scanner(emails);
            Scanner scnumero = new Scanner(nomes);
            while(scsenha.hasNext() && scemail.hasNext() && scnumero.hasNext()){
                senha.add(scsenha.nextLine());
                email.add(scemail.nextLine());
                nome.add(scnumero.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } 
        if (buscarRelacao(email, senha)){
            JOptionPane.showMessageDialog(rootPane, "Login realizado. Seja bem-vindo(a), "+nome.get(buscarRelacaoInt(email))+"!");
            dispose();
        }
        }
    }//GEN-LAST:event_SenhaKeyPressed
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnLogin;
    private javax.swing.JTextField Login;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel OlhoAberto;
    private javax.swing.JLabel OlhoFechado;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
